currentDeployment: default
deploymentConfigurations:
- name: default
  version: 2.5.2
  providers:
    kubernetes:
      enabled: true
      accounts:
      - name: spinnaker
        providerVersion: V2
        namespaces:
        - spinnaker
        kubeconfigFile: /home/spinnaker/.hal/secret/kubeconfig-spinnaker-sa
        onlySpinnakerManaged: true
      - name: kubernetes
        providerVersion: V2
        omitNamespaces:
        - spinnaker
        kubeconfigFile: /home/spinnaker/.hal/secret/kubeconfig-all-sa
        onlySpinnakerManaged: true
      primaryAccount: spinnaker
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: spinnaker
    location: spinnaker
  persistentStorage:
    persistentStoreType: s3
    s3:
      bucket: BUCKET_NAME
      rootFolder: front50
      region: REGION
  security:
    apiSecurity:
      overrideBaseUrl: http://GATE_ENDPOINT
    uiSecurity:
      overrideBaseUrl: http://DECK_ENDPOINT
  features:
    artifacts: true
  artifacts:
    http:
      enabled: true
  armory:
    diagnostics:
      enabled: true
      logging:
        enabled: true